// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "production" | "development";
	JWT_ISSUER: "nxt-energy-platform";
	API_BASE_URL: "https://et.vantax.co.za/api" | "http://localhost:8787";
	ORDER_BOOK: DurableObjectNamespace<import("./src/index").OrderBookDO>;
	ESCROW_MGR: DurableObjectNamespace<import("./src/index").EscrowManagerDO>;
	P2P_MATCHER: DurableObjectNamespace<import("./src/index").P2PMatcherDO>;
	SMART_CONTRACT: DurableObjectNamespace<import("./src/index").SmartContractDO>;
	RISK_ENGINE: DurableObjectNamespace<import("./src/index").RiskEngineDO>;
	R2: R2Bucket;
	DB: D1Database;
	EVENTS_QUEUE: Queue;
	AI: Ai;
}
